### ISSUE TITLE
open repo wiki?

### ISSUE THREAD

**Issue by Javran** [cyrismustang/k2badge#1]
Could you create a repo wiki page? I think I can help to write some document about how to prepare POST data and let other KC tools developers know.

thanks xD

**Comment by cyrismustang** [comment]
Sure!  Should be done

**Comment by Javran** [comment]
I just wrote the wiki: https://github.com/cyrismustang/k2badge/wiki
enjoy!

**Comment by cyrismustang** [comment]
@Javran Thanks for your contribution!
