### ISSUE TITLE
can't export badge to site

### ISSUE THREAD

**Issue by amazingfate** [cyrismustang/k2badge#12]
I use the latest kc3kai

**Comment by Nya-chan** [comment]
@amazingfate Can you post the export data? I just tested it and it worked fine, but there might be some data missing.

In Chrome right click the "export" button in the strategy room, and get to nearby "dummy_section" and copy fleets and ships code here. Looks like this:
![image](https://user-images.githubusercontent.com/1585104/60368885-4af1b280-99f2-11e9-9962-627d34c8accd.png)

**Comment by amazingfate** [comment]
@Nya-chan there is no data. 
![image](https://user-images.githubusercontent.com/5022901/60380737-0101de80-9a7d-11e9-9599-e0af1db80d23.png)

**Comment by amazingfate** [comment]
might be something wrong with my network connections, works in my company network

**Comment by Nya-chan** [comment]
If you encounter it further, report it to KC3Kai instead, please - they generate the data on their end, so missing data means there was some problems between the game and KC3Kai, likely. K2Badge just receives the data, I can't do much in this repo with how they are generated.
