### ISSUE TITLE
ooshio kai 2 update

### ISSUE THREAD

**Issue by Javran** [cyrismustang/k2badge#3]
looks like you've updated the website, but few things are still missing:
- fleet tab: ooshio2 pictures
- k2 tab: ooshi kai 2 not set
- poster collection: ooshio is missing if remodelled to her kai2

hopefully PR #2  should fix most problems. also fyi: ooshio kai 2's master id is 199.

**Comment by cyrismustang** [comment]
@Javran Can you clear cache and try again?  I don't have ooshio k2 so you might test this better.

**Comment by Javran** [comment]
@cyrismustang I can confirm everything works fine now, thanks!
