### ISSUE TITLE
asashio k2 not checked

### ISSUE THREAD

**Issue by Javran** [cyrismustang/k2badge#6]
asashio k2 is not checked when exporting from KC3Kai, I'm sure asashio k2's master id 463 does show up in the ship list posted.
I also suspect asashio k2d might experience same problem but mine still has few levels to go.

**Comment by cyrismustang** [comment]
@Javran I don't have asashio k2 but have you tried clearing cache?

**Comment by cyrismustang** [comment]
Checking using my testing tool, 463 does generate Asashio on the badge after cache refresh.

**Comment by Javran** [comment]
@cyrismustang sorry, turns out to be my fault. will check if k2d works (hopefully it will) when I make her to lvl 85.

closing.
