### ISSUE TITLE
Kamikaze Kai & I-26 ship id messed up

### ISSUE THREAD

**Issue by Javran** [cyrismustang/k2badge#7]
I think kamikaze & I-26's master id could have been messed up:
- Kamikaze Kai's master id is 476, but if I just pass `[476]` as ship list, I got I-26
- I-26's is 483, just passing `[483]` as ship list results in nothing being selected

just to make it more clear, here are few related master ids:
- Kamikaze (471), Kamikaze Kai (476)
- I-26 (483), I-26 Kai (367)

**Comment by cyrismustang** [comment]
For some reason I extracted the wrong ID for Nimu, I had her as 476.  I changed her ID to 483 and should be fixed after browser cache clear.

**Comment by Javran** [comment]
thanks! I can confirm it's fixed now, closing.
